In [345]:
import pandas as pd
import numpy as np

In [346]:
df = pd.read_csv("../data/bank-additional-full.csv", sep=";")

In [347]:
display(df.head())
df.info()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [348]:
display(df.isna().sum())
(df == "unknown").sum()
# se usar o comando comum, mostra que não tem ausentes, mas os ausentes estão como texto "unknown"
# depois é possível ver realmente quantos ausentes se tem no dataset

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

age                  0
job                330
marital             80
education         1731
default           8597
housing            990
loan               990
contact              0
month                0
day_of_week          0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx       0
cons.conf.idx        0
euribor3m            0
nr.employed          0
y                    0
dtype: int64

In [349]:
df.replace("unknown", np.nan, inplace=True)
df.isna().sum()
# Substitui unknown por np.nan para reconhecimento do pandas

age                  0
job                330
marital             80
education         1731
default           8597
housing            990
loan               990
contact              0
month                0
day_of_week          0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx       0
cons.conf.idx        0
euribor3m            0
nr.employed          0
y                    0
dtype: int64

In [350]:
for col in df.columns:
    if df[col].mode().empty == False:
        df[col] = df[col].fillna(df[col].mode()[0])

df.isna().sum()
# Substitui os valores ausentes das colunas não vazias pela moda da respectiva coluna

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [351]:
df.duplicated().sum()

np.int64(14)

In [352]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()
# Remove duplicatas

np.int64(0)

In [353]:
df["contatado_antes"] = (df["pdays"] != 999).astype(int)
# Cria uma colona chamada "contatado_antes" considerando o valor 999 na coluna pdays como 0 (nunca foi contatado)

In [354]:
df["pdays"].replace(999, 0, inplace=True)
# Substitui o indicador de nunca contatado da coluna "pdays" por 0, para fins de coerência com a coluna "contatado_antes"

C:\Users\yangi\AppData\Local\Temp\ipykernel_15728\2051079650.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["pdays"].replace(999, 0, inplace=True)

In [355]:
df = df.replace({'no': 0, 'yes': 1})
# Substitui 'no' por 0 e 'yes' por 1 em todo o DataFrame

C:\Users\yangi\AppData\Local\Temp\ipykernel_15728\1780105226.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({'no': 0, 'yes': 1})

In [356]:
df["faixa_etaria"] = pd.cut(
    df["age"],
    bins=[0, 25, 35, 50, 65, 100],
    labels=["ate_25", "26_35", "36_50", "51_65", "acima_65"]
)
# criado uma coluna para transformar as idades numéricas em categorias, vai ajudar a gente na questão de probabilidade depois

In [357]:
df.groupby("faixa_etaria")["y"].value_counts(normalize=True)
# foi agrupado e calculado a proporção de yes e no de cada idade

C:\Users\yangi\AppData\Local\Temp\ipykernel_15728\3458501838.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("faixa_etaria")["y"].value_counts(normalize=True)

faixa_etaria  y
ate_25        0    0.790390
              1    0.209610
26_35         0    0.882773
              1    0.117227
36_50         0    0.916062
              1    0.083938
51_65         0    0.879250
              1    0.120750
acima_65      0    0.530744
              1    0.469256
Name: proportion, dtype: float64

In [358]:
df["faixa_campaign"] = pd.cut(
    df["campaign"],
    bins=[0, 1, 3, 6, 60],
    labels=["1", "2a3", "4a6", "mais_6"]
)
# mesmo esquema da faixa_etaria

In [359]:
df[["age", "campaign", "previous", "duration"]].describe()
# outliers analisados, pois representam situações possíveis no contexto das campanhas
# a variável campaign possui valor máximo bem maior que a mediano, então se tem contatos muito acima do padrão

                age      campaign      previous      duration
count  41174.000000  41174.000000  41174.000000  41174.000000
mean      40.023583      2.567956      0.173022    258.323627
std       10.420578      2.770364      0.494975    259.309058
min       17.000000      1.000000      0.000000      0.000000
25%       32.000000      1.000000      0.000000    102.000000
50%       38.000000      2.000000      0.000000    180.000000
75%       47.000000      3.000000      0.000000    319.000000
max       98.000000     56.000000      7.000000   4918.000000

In [360]:
# Conversão para categórica ordinal: education
ordem_educacao = ['illiterate', 'basic.4y', 'basic.6y', 'basic.9y', 'high.school', 'professional.course', 'university.degree']
df['education'] = pd.Categorical(df['education'], categories=ordem_educacao, ordered=True)

In [361]:
# Conversão para categórica ordinal: month e day_of_week
ordem_mes = ['mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']
ordem_dia = ['mon', 'tue', 'wed', 'thu', 'fri']

df['month'] = pd.Categorical(df['month'], categories=ordem_mes, ordered=True)
df['day_of_week'] = pd.Categorical(df['day_of_week'], categories=ordem_dia, ordered=True)

In [362]:
# Conversão para categórica nominal: demais colunas
colunas_nominais = ['job', 'marital', 'default', 'housing', 'loan', 'contact', 'poutcome', 'y', 'contatado_antes']

for col in colunas_nominais:
    df[col] = df[col].astype('category')

In [363]:
df_eda = df.copy()
df = df.drop(columns=['duration'])
# A coluna 'duration' causaria conflito no uso dos algoritmos de machine learning
# Mas a coluna será mantida para usar na EDA, para entender o comportamento das chamadas

In [364]:
df.to_parquet('dados_limpos.parquet', index = False)
# Arquivo sem o "duration"
df_eda.to_parquet('dados_eda.parquet', index = False)
# Arquivo com o "duration" para o EDA